name: CI
on: [push, workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: amazon-corretto@1.17.0-0.35.1
      - run: sbt compile
      - run: sudo apt install -y libcurl4-openssl-dev
      - run: sbt nativeLink
      - uses: windymelt/psi-mackerel@eaaa714afdc98872bf9c7e2a9919b5963bd17883
        with:
          urls: |
            https://example.com/
            https://www.3qe.us/
          mackerel_api_token: "" # for test
          mackerel_service: "" # for test

