name: CI
on: [push, workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: amazon-corretto@1.17.0-0.35.1
      - run: sbt nativeLink
