name: CI
on: [push, workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.17
      - run: sbt nativeLink
